GET http://localhost:3001/api/patients
###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Thiwanka Somachandra",
    "ssn": "090388-399T",
    "dateOfBirth": "1988-03-09",
    "gender": "male",
    "occupation": "Full Stack Developer"
}

###
POST http://localhost:3001/api/patients/dc7b26fa-b0a2-4aee-8637-0d7fe72b50fd/entries
Content-Type: application/json

{
    "date": "2019-10-20",
    "specialist" : "MD House",
    "type": "OccupationalHealthcare",
    "description" : "Test medical entry",
    "employerName" : "Tervestalo"
}