###
GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "mluukkai",
    "name" : "Matti Luukkalainen",
    "password" : "salainen"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "thiwankas",
    "name" : "Thiwanka Somachandra",
    "password" : "sa"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "th",
    "name" : "Thiwanka Somachandra",
    "password" : "salainen"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "",
    "name" : "Thiwanka Somachandra",
    "password" : ""
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "hellas",
    "name" : "Arto Hellas",
    "password" : "salainen"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "userId" : "655fa6fa1727b51bf820f05d",
    "title": "What Are the React Team Principles?",
    "author": "Dan Abramov",
    "url": "https://overreacted.io/what-are-the-react-team-principles/",
    "likes": 5000
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "userId" : "656167723544a5c129d77782",
    "title": "Microservices - a definition of this new architectural term",
    "author": "Martin Flower",
    "url": "https://martinfowler.com/tags/microservices.html",
    "likes": 3000
}