POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Node.js",
    "author": "Dave Gray",
    "url": "https://courses.davegray.codes/view",
    "likes": 3000
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Nest.js",
    "author": "Siheli Methunima",
    "url": "https://nestjs.com/",
    "likes": 7000
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Shell Scripting",
    "author": "Ishan Herath",
    "url": "https://www.coursera.org/articles/what-is-shell-scripting",
    "likes": 5000
}
###
GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "mluukkai",
    "name" : "Matti Luukkalainen",
    "password" : "salainen"
}